# Generated by Django 2.2.3 on 2021-05-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_comentariosubcategoria_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imgPerfil',
            field=models.ImageField(default='', upload_to='Perifl'),
        ),
    ]
