# Generated by Django 2.2.3 on 2021-05-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0004_usuario_imgperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorias',
            name='titulo',
            field=models.CharField(default='', max_length=150),
        ),
    ]
