# Generated by Django 2.2.3 on 2021-05-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0006_subcategorias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorias',
            name='videoIntro',
            field=models.CharField(blank=True, default='https://www.youtube.com/embed/', max_length=1000, null=True),
        ),
    ]
