# Generated by Django 2.2.3 on 2021-05-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0007_auto_20210518_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorias',
            name='autor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subcategorias',
            name='consejo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
