# Generated by Django 2.2.3 on 2021-05-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0008_auto_20210518_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorias',
            name='visto',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
