# Generated by Django 2.2.3 on 2021-05-20 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0010_subcategorias_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default='', null=True, upload_to='ImgCategoria'),
        ),
        migrations.AlterField(
            model_name='comentariosubcategoria',
            name='fecha',
            field=models.CharField(default=datetime.date(2021, 5, 20), max_length=10),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='fecha',
            field=models.CharField(default=datetime.date(2021, 5, 20), max_length=10),
        ),
    ]
