# Generated by Django 2.2.3 on 2021-05-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0013_subcategorias_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorias',
            old_name='home',
            new_name='principal',
        ),
    ]
