# Generated by Django 2.2.3 on 2021-05-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0015_informacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='telefono',
            field=models.CharField(default=1234567890, max_length=10, null=True),
        ),
    ]
