# Generated by Django 2.2.3 on 2021-05-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0016_suscripcion_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='email',
            field=models.EmailField(default='', max_length=254, null=''),
        ),
    ]
