# Generated by Django 2.2.3 on 2021-05-22 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0020_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariosubcategoria',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comentariosubcategoria',
            name='nombre',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='comentariosubcategoria',
            name='fecha',
            field=models.CharField(default=datetime.date(2021, 5, 22), max_length=10),
        ),
        migrations.AlterField(
            model_name='comentariosubcategoria',
            name='usuario',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='a.Usuario'),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='fecha',
            field=models.CharField(default=datetime.date(2021, 5, 22), max_length=10),
        ),
    ]
