# Generated by Django 3.2.3 on 2021-05-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0021_auto_20210522_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariosubcategoria',
            name='like',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
    ]
