# Generated by Django 3.2.4 on 2021-06-27 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0023_respuestascomentariossubcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Podcast')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='comentariosubcategoria',
            name='like',
        ),
        migrations.AlterField(
            model_name='comentariosubcategoria',
            name='fecha',
            field=models.CharField(default=datetime.date(2021, 6, 27), max_length=10),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='fecha',
            field=models.CharField(default=datetime.date(2021, 6, 27), max_length=10),
        ),
        migrations.DeleteModel(
            name='respuestasComentariosSubcategoria',
        ),
    ]
