# Generated by Django 3.2.4 on 2021-06-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0024_auto_20210627_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
