# Generated by Django 2.2.3 on 2021-07-02 14:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0026_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariosubcategoria',
            name='fecha',
            field=models.CharField(default=datetime.date(2021, 7, 2), max_length=10),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='fecha',
            field=models.CharField(default=datetime.date(2021, 7, 2), max_length=10),
        ),
        migrations.CreateModel(
            name='CompraCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.subCategorias')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.Usuario')),
            ],
        ),
    ]
