# Generated by Django 2.2.3 on 2021-07-03 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0027_auto_20210702_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ImagenCursos'),
        ),
        migrations.AlterField(
            model_name='comentariosubcategoria',
            name='fecha',
            field=models.CharField(default=datetime.date(2021, 7, 3), max_length=10),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='fecha',
            field=models.CharField(default=datetime.date(2021, 7, 3), max_length=10),
        ),
    ]
